/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pract1;

import org.slf4j.LoggerFactory;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


@SpringBootApplication
public class Library {
public static org.slf4j.Logger logger=LoggerFactory.getLogger(Library.class);
	public static void main(String[] args) {
		logger.info("Welcome Application Started.............................................................");
		SpringApplication.run(Library.class, args);
	}

}
