/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pract1;


import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;



@SpringBootTest
class LibraryTest {

	@Test
	void contextLoads() {
	}

}